"""remove_email_from_usuario

Revision ID: 178589bf4bd3
Revises: a5f3c8d9e012
Create Date: 2026-04-06 11:55:00.713172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '178589bf4bd3'
down_revision: Union[str, None] = 'a5f3c8d9e012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'email', schema='rrhh')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=True), schema='rrhh')
    # ### end Alembic commands ###
