"""semana6_asistencia_diaria

Revision ID: 18fbcc39fce1
Revises: f3b939aeeb88
Create Date: 2026-04-07 13:27:53.299409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18fbcc39fce1'
down_revision: Union[str, None] = 'f3b939aeeb88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asistencia_diaria',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_empleado', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('id_marcacion_entrada', sa.BigInteger(), nullable=True),
    sa.Column('id_marcacion_salida', sa.BigInteger(), nullable=True),
    sa.Column('id_justificacion', sa.Integer(), nullable=True),
    sa.Column('tipo_dia', sa.String(length=20), nullable=False, comment='Estado del día: presente, ausente, feriado, descanso, presente_exento, etc.'),
    sa.Column('minutos_retraso', sa.Integer(), nullable=False, comment='Minutos de retraso respecto al horario asignado (considerando tolerancia)'),
    sa.Column('minutos_trabajados', sa.Integer(), nullable=False, comment='Minutos netos trabajados (SALIDA - ENTRADA), sin descuento de almuerzo'),
    sa.Column('horas_extra', sa.Numeric(precision=4, scale=1), nullable=False, comment='Horas extra trabajadas (calculadas si excede horario normal)'),
    sa.Column('horas_permiso_usadas', sa.Numeric(precision=4, scale=1), nullable=False, comment='Horas de permiso consumidas (desnormalizado de justificacion_ausencia)'),
    sa.Column('trabajo_en_feriado', sa.Boolean(), nullable=False, comment='TRUE si el empleado marcó en un día feriado. Si !es_cargo_confianza, suma 8h a vacación'),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_empleado'], ['rrhh.empleado.id'], name=op.f('fk_asistencia_diaria_id_empleado_empleado'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_marcacion_entrada'], ['rrhh.marcacion.id'], name=op.f('fk_asistencia_diaria_id_marcacion_entrada_marcacion'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_marcacion_salida'], ['rrhh.marcacion.id'], name=op.f('fk_asistencia_diaria_id_marcacion_salida_marcacion'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asistencia_diaria')),
    sa.UniqueConstraint('id_empleado', 'fecha', name='uq_asistencia_dia'),
    schema='rrhh'
    )
    op.create_index('idx_asistencia_empleado_fecha', 'asistencia_diaria', ['id_empleado', 'fecha'], unique=False, schema='rrhh')
    op.create_index(op.f('ix_rrhh_asistencia_diaria_fecha'), 'asistencia_diaria', ['fecha'], unique=False, schema='rrhh')
    # ### end Alembic commands ###
    
    # ============================================================
    # VISTA v_asistencia_mensual (NO detectada por autogenerate)
    # Resumen mensual de asistencia para reportes al Ministerio
    # ============================================================
    op.execute("""
        CREATE OR REPLACE VIEW rrhh.v_asistencia_mensual AS
        SELECT
            e.id                            AS id_empleado,
            e.nombres || ' ' || e.apellidos AS nombre_completo,
            c.nombre                        AS cargo,
            c.es_cargo_confianza,
            d.nombre                        AS departamento,
            DATE_TRUNC('month', ad.fecha)   AS mes,
            COUNT(*)                        AS total_dias_registro,
            COUNT(*) FILTER (WHERE ad.tipo_dia = 'presente')          AS dias_presente,
            COUNT(*) FILTER (WHERE ad.tipo_dia = 'presente_exento')   AS dias_presente_exento,
            COUNT(*) FILTER (WHERE ad.tipo_dia = 'ausente')           AS dias_ausente,
            COUNT(*) FILTER (WHERE ad.tipo_dia = 'feriado')           AS dias_feriado,
            COUNT(*) FILTER (WHERE ad.tipo_dia = 'permiso_parcial')   AS dias_permiso_parcial,
            COUNT(*) FILTER (WHERE ad.tipo_dia = 'licencia_medica')   AS dias_licencia_medica,
            COUNT(*) FILTER (WHERE ad.tipo_dia = 'descanso')          AS dias_descanso,
            SUM(ad.minutos_retraso)                                   AS total_minutos_retraso,
            SUM(ad.minutos_trabajados)                                AS total_minutos_trabajados,
            SUM(ad.horas_extra)                                       AS total_horas_extra,
            COUNT(*) FILTER (WHERE ad.trabajo_en_feriado = TRUE)      AS dias_trabajados_en_feriado
        FROM rrhh.asistencia_diaria ad
        JOIN rrhh.empleado e ON e.id = ad.id_empleado
        JOIN rrhh.cargo    c ON c.id = e.id_cargo
        JOIN rrhh.departamento d ON d.id = e.id_departamento
        GROUP BY e.id, e.nombres, e.apellidos, c.nombre, c.es_cargo_confianza,
                 d.nombre, DATE_TRUNC('month', ad.fecha);
        
        COMMENT ON VIEW rrhh.v_asistencia_mensual IS
        'Resumen mensual de asistencia para el reporte OVT del Ministerio de Trabajo. Incluye todos los tipos de día y contadores de feriados trabajados.';
    """)


def downgrade() -> None:
    # ============================================================
    # ELIMINAR VISTA v_asistencia_mensual primero
    # ============================================================
    op.execute("DROP VIEW IF EXISTS rrhh.v_asistencia_mensual;")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rrhh_asistencia_diaria_fecha'), table_name='asistencia_diaria', schema='rrhh')
    op.drop_index('idx_asistencia_empleado_fecha', table_name='asistencia_diaria', schema='rrhh')
    op.drop_table('asistencia_diaria', schema='rrhh')
    # ### end Alembic commands ###
