"""semana3_modulo_employees_completo

Revision ID: 2df89d16a050
Revises: 67b62f60bfa9
Create Date: 2026-03-31 13:47:34.143880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2df89d16a050'
down_revision: Union[str, None] = '67b62f60bfa9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('horario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False, comment="Ej: 'Turno Oficina', 'Turno Noche'"),
    sa.Column('hora_entrada', sa.Time(), nullable=False),
    sa.Column('hora_salida', sa.Time(), nullable=False),
    sa.Column('tolerancia_minutos', sa.Integer(), nullable=False, comment='Minutos de gracia para considerar retraso'),
    sa.Column('jornada_semanal_horas', sa.Numeric(precision=4, scale=1), nullable=False, comment='Total horas semanales (máx 48 según LGT Art. 46)'),
    sa.Column('dias_laborables', sa.JSON(), nullable=False, comment='Array de días laborables [1=Lun, 2=Mar, ..., 7=Dom]'),
    sa.Column('tipo_jornada', sa.Enum('continua', 'discontinua', name='tipo_jornada_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_horario')),
    schema='rrhh'
    )
    op.create_table('asignacion_horario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_empleado', sa.Integer(), nullable=False),
    sa.Column('id_horario', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True, comment='NULL = asignación vigente indefinidamente'),
    sa.Column('es_activo', sa.Boolean(), nullable=False, comment='Solo una asignación activa por empleado en una fecha'),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_empleado'], ['rrhh.empleado.id'], name=op.f('fk_asignacion_horario_id_empleado_empleado'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_horario'], ['rrhh.horario.id'], name=op.f('fk_asignacion_horario_id_horario_horario'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_asignacion_horario')),
    schema='rrhh'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asignacion_horario', schema='rrhh')
    op.drop_table('horario', schema='rrhh')
    # ### end Alembic commands ###
