"""agregar tipo_incidencia inconsistente

Revision ID: 4fe73b669ee1
Revises: 5f2fff828236
Create Date: 2026-05-29 23:18:31.055557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fe73b669ee1'
down_revision: Union[str, None] = '5f2fff828236'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('horario', 'horas_trabajadas', schema='rrhh')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('horario', sa.Column('horas_trabajadas', sa.NUMERIC(precision=4, scale=2), autoincrement=False, nullable=True, comment='Horas trabajadas calculadas automáticamente (NULL para jornada discontinua)'), schema='rrhh')
    # ### end Alembic commands ###
