"""semana3_jornada_semanal_calculada

Revision ID: 5f2fff828236
Revises: f02c0b4996e1
Create Date: 2026-05-24 00:17:20.122297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f2fff828236'
down_revision: Union[str, None] = 'f02c0b4996e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('horario', 'jornada_semanal_horas',
               existing_type=sa.NUMERIC(precision=4, scale=1),
               type_=sa.Numeric(precision=4, scale=2),
               nullable=True,
               comment='Total horas semanales (máx 48 según LGT Art. 46) - calculado automáticamente',
               existing_comment='Total horas semanales (máx 48 según LGT Art. 46)',
               schema='rrhh')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('horario', 'jornada_semanal_horas',
               existing_type=sa.Numeric(precision=4, scale=2),
               type_=sa.NUMERIC(precision=4, scale=1),
               nullable=False,
               comment='Total horas semanales (máx 48 según LGT Art. 46)',
               existing_comment='Total horas semanales (máx 48 según LGT Art. 46) - calculado automáticamente',
               schema='rrhh')
    # ### end Alembic commands ###
