"""semana2_auth_usuario

Revision ID: 67b62f60bfa9
Revises: 6a65fa2dd1f5
Create Date: 2026-03-27 12:54:08.263683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67b62f60bfa9'
down_revision: Union[str, None] = '6a65fa2dd1f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Contraseña hasheada con bcrypt'),
    sa.Column('id_rol', sa.Integer(), nullable=False),
    sa.Column('id_empleado', sa.Integer(), nullable=True, comment='NULL para usuarios sin registro de empleado (ej: admin externo)'),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_empleado'], ['rrhh.empleado.id'], name=op.f('fk_usuario_id_empleado_empleado'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_rol'], ['rrhh.rol.id'], name=op.f('fk_usuario_id_rol_rol'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuario')),
    sa.UniqueConstraint('id_empleado', name=op.f('uq_usuario_id_empleado')),
    sa.UniqueConstraint('username', name=op.f('uq_usuario_username')),
    schema='rrhh'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario', schema='rrhh')
    # ### end Alembic commands ###
