"""semana3_horario_discontinuo_y_contrato

Revision ID: 797d9b7a1cfb
Revises: 1ec7e965e7ea
Create Date: 2026-05-23 20:27:53.929610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '797d9b7a1cfb'
down_revision: Union[str, None] = '1ec7e965e7ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('horario', 'hora_entrada',
               existing_type=postgresql.TIME(),
               nullable=True,
               schema='rrhh')
    op.alter_column('horario', 'hora_salida',
               existing_type=postgresql.TIME(),
               nullable=True,
               schema='rrhh')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('horario', 'hora_salida',
               existing_type=postgresql.TIME(),
               nullable=False,
               schema='rrhh')
    op.alter_column('horario', 'hora_entrada',
               existing_type=postgresql.TIME(),
               nullable=False,
               schema='rrhh')
    # ### end Alembic commands ###
