"""semana8_modulo_reports

Revision ID: cfc064401f07
Revises: e6c69cc6f904
Create Date: 2026-04-10 11:18:44.378073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'cfc064401f07'
down_revision: Union[str, None] = 'e6c69cc6f904'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reporte',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo_reporte', sa.Enum('asistencia_mensual', 'planilla', 'vacaciones', 'individual', name='tipo_reporte_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id_generado_por', sa.Integer(), nullable=True),
    sa.Column('id_departamento', sa.Integer(), nullable=True),
    sa.Column('id_empleado', sa.Integer(), nullable=True),
    sa.Column('periodo_inicio', sa.Date(), nullable=False),
    sa.Column('periodo_fin', sa.Date(), nullable=False),
    sa.Column('ruta_archivo', sa.String(length=255), nullable=False),
    sa.Column('formato', sa.Enum('PDF', 'XLSX', 'CSV', name='formato_reporte_enum', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('fecha_generacion', sa.DateTime(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('periodo_fin >= periodo_inicio', name=op.f('ck_reporte_chk_reporte_periodo')),
    sa.ForeignKeyConstraint(['id_departamento'], ['rrhh.departamento.id'], name=op.f('fk_reporte_id_departamento_departamento'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_empleado'], ['rrhh.empleado.id'], name=op.f('fk_reporte_id_empleado_empleado'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_generado_por'], ['rrhh.usuario.id'], name=op.f('fk_reporte_id_generado_por_usuario'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reporte')),
    schema='rrhh'
    )
    # ### end Alembic commands ###

    # Vista para soporte de reportes de planilla mensual
    op.execute(
        """
        CREATE OR REPLACE VIEW rrhh.v_saldo_impuestos_planilla AS
        WITH base AS (
            SELECT
                vam.id_empleado,
                vam.nombre_completo,
                vam.cargo,
                e.id_departamento,
                vam.departamento,
                vam.mes,
                e.salario_base,
                COALESCE(vam.total_minutos_retraso, 0) AS minutos_retraso_mes,
                COALESCE(vam.dias_ausente, 0) AS dias_ausente_mes,
                (vam.mes + INTERVAL '1 month - 1 day')::date AS fecha_corte_impuesto
            FROM rrhh.v_asistencia_mensual vam
            JOIN rrhh.empleado e ON e.id = vam.id_empleado
        ),
        descuentos_base AS (
            SELECT
                b.*,
                ROUND((b.salario_base * b.minutos_retraso_mes::numeric) / 14400, 2) AS descuento_retraso_bs,
                ROUND((b.salario_base * b.dias_ausente_mes::numeric) / 30, 2) AS descuento_ausencia_bs
            FROM base b
        ),
        imponible AS (
            SELECT
                d.*,
                ROUND(d.salario_base - d.descuento_retraso_bs - d.descuento_ausencia_bs, 2) AS salario_descuento_preimpuestos
            FROM descuentos_base d
        ),
        con_tasas AS (
            SELECT
                i.*,
                COALESCE(afp.porcentaje, 0)::numeric(5,2) AS porcentaje_afp_laboral,
                COALESCE(rciva.porcentaje, 0)::numeric(5,2) AS porcentaje_rc_iva
            FROM imponible i
            LEFT JOIN LATERAL (
                SELECT p.porcentaje
                FROM rrhh.parametro_impuesto p
                WHERE p.nombre = 'AFP_LABORAL'
                  AND p.fecha_vigencia_inicio <= i.fecha_corte_impuesto
                  AND (p.fecha_vigencia_fin IS NULL OR p.fecha_vigencia_fin >= i.fecha_corte_impuesto)
                ORDER BY p.fecha_vigencia_inicio DESC
                LIMIT 1
            ) afp ON TRUE
            LEFT JOIN LATERAL (
                SELECT p.porcentaje
                FROM rrhh.parametro_impuesto p
                WHERE p.nombre = 'RC_IVA'
                  AND p.fecha_vigencia_inicio <= i.fecha_corte_impuesto
                  AND (p.fecha_vigencia_fin IS NULL OR p.fecha_vigencia_fin >= i.fecha_corte_impuesto)
                ORDER BY p.fecha_vigencia_inicio DESC
                LIMIT 1
            ) rciva ON TRUE
        )
        SELECT
            ct.id_empleado,
            ct.nombre_completo,
            ct.cargo,
            ct.id_departamento,
            ct.departamento,
            ct.mes,
            ct.salario_base,
            ct.minutos_retraso_mes,
            ct.dias_ausente_mes,
            ct.descuento_retraso_bs,
            ct.descuento_ausencia_bs,
            ct.salario_descuento_preimpuestos,
            ct.porcentaje_afp_laboral,
            ROUND((ct.salario_descuento_preimpuestos * ct.porcentaje_afp_laboral) / 100, 2) AS monto_afp_laboral,
            ct.porcentaje_rc_iva,
            ROUND((ct.salario_descuento_preimpuestos * ct.porcentaje_rc_iva) / 100, 2) AS monto_rc_iva,
            ROUND(
                (ct.salario_descuento_preimpuestos * ct.porcentaje_afp_laboral) / 100
                + (ct.salario_descuento_preimpuestos * ct.porcentaje_rc_iva) / 100,
                2
            ) AS total_descuentos,
            ROUND(
                ct.salario_descuento_preimpuestos
                - ((ct.salario_descuento_preimpuestos * ct.porcentaje_afp_laboral) / 100)
                - ((ct.salario_descuento_preimpuestos * ct.porcentaje_rc_iva) / 100),
                2
            ) AS salario_neto_estimado
        FROM con_tasas ct;
        """
    )


def downgrade() -> None:
    op.execute("DROP VIEW IF EXISTS rrhh.v_saldo_impuestos_planilla;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reporte', schema='rrhh')
    # ### end Alembic commands ###
