"""semana7_feriados_justificaciones_vacaciones

Revision ID: e6c69cc6f904
Revises: 18fbcc39fce1
Create Date: 2026-04-08 11:35:43.863521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6c69cc6f904'
down_revision: Union[str, None] = '18fbcc39fce1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dia_festivo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('descripcion', sa.String(length=150), nullable=False, comment="Descripción del feriado (ej: 'Día del Trabajo', 'Aniversario de La Paz')"),
    sa.Column('ambito', sa.Enum('NACIONAL', 'DEPARTAMENTAL', name='ambito_festivo_enum', native_enum=True, create_constraint=True, schema='rrhh'), nullable=False, comment='NACIONAL aplica a todos, DEPARTAMENTAL solo al departamento indicado'),
    sa.Column('codigo_departamento', sa.String(length=2), nullable=True, comment='NULL solo para NACIONAL. DEPARTAMENTAL requiere el código (LP, CB, SC, etc.)'),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['codigo_departamento'], ['rrhh.complemento_dep.codigo'], name=op.f('fk_dia_festivo_codigo_departamento_complemento_dep'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dia_festivo')),
    sa.UniqueConstraint('fecha', 'ambito', 'codigo_departamento', name='uq_dia_festivo'),
    schema='rrhh'
    )
    op.create_index(op.f('ix_rrhh_dia_festivo_fecha'), 'dia_festivo', ['fecha'], unique=False, schema='rrhh')
    op.create_table('beneficio_cumpleanos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_empleado', sa.Integer(), nullable=False),
    sa.Column('gestion', sa.Integer(), nullable=False, comment='Año de la gestión (ej: 2026)'),
    sa.Column('fue_utilizado', sa.Boolean(), nullable=False, comment='TRUE si el empleado usó el beneficio'),
    sa.Column('fecha_uso', sa.DateTime(), nullable=True, comment='Fecha/hora en que se usó el beneficio'),
    sa.Column('id_justificacion', sa.Integer(), nullable=True, comment='FK a justificacion_ausencia si el empleado solicitó usar el beneficio'),
    sa.Column('transferido_a_vacacion', sa.Boolean(), nullable=False, comment='TRUE si las 4h ya fueron sumadas al saldo vacacional'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_empleado'], ['rrhh.empleado.id'], name=op.f('fk_beneficio_cumpleanos_id_empleado_empleado'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_beneficio_cumpleanos')),
    sa.UniqueConstraint('id_empleado', 'gestion', name='uq_beneficio_empleado_gestion'),
    schema='rrhh'
    )
    op.create_table('justificacion_ausencia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_empleado', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False, comment='Primer día de la ausencia o permiso'),
    sa.Column('fecha_fin', sa.Date(), nullable=False, comment='Último día de la ausencia o permiso (puede ser igual a fecha_inicio)'),
    sa.Column('tipo_justificacion', sa.Enum('permiso_personal', 'licencia_medica_accidente', 'cumpleanos', 'vacacion_por_horas', name='tipo_justificacion_enum', native_enum=True, create_constraint=True, schema='rrhh'), nullable=False),
    sa.Column('tipo_permiso', sa.Enum('dia_completo', 'por_horas', name='tipo_permiso_enum', native_enum=True, create_constraint=True, schema='rrhh'), nullable=False),
    sa.Column('es_por_horas', sa.Boolean(), nullable=False, comment='TRUE si el permiso es por fracción de jornada (por_horas)'),
    sa.Column('hora_inicio_permiso', sa.Time(), nullable=True, comment='Hora de inicio del permiso (solo si es_por_horas=TRUE)'),
    sa.Column('hora_fin_permiso', sa.Time(), nullable=True, comment='Hora de fin del permiso (solo si es_por_horas=TRUE)'),
    sa.Column('total_horas_permiso', sa.Numeric(precision=4, scale=1), nullable=True, comment='Total de horas del permiso. Calculado automáticamente por backend'),
    sa.Column('descripcion', sa.Text(), nullable=True, comment='Descripción o motivo del permiso'),
    sa.Column('documento_url', sa.String(length=255), nullable=True, comment='URL al documento de respaldo (certificado médico, etc.)'),
    sa.Column('estado_aprobacion', sa.Enum('pendiente', 'aprobado', 'rechazado', name='estado_aprobacion_enum', native_enum=True, create_constraint=True, schema='rrhh'), nullable=False),
    sa.Column('id_aprobado_por', sa.Integer(), nullable=True, comment='ID del empleado (supervisor o RRHH) que aprobó/rechazó'),
    sa.Column('fecha_aprobacion', sa.DateTime(), nullable=True, comment='Fecha/hora en que se aprobó o rechazó'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_aprobado_por'], ['rrhh.empleado.id'], name=op.f('fk_justificacion_ausencia_id_aprobado_por_empleado'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_empleado'], ['rrhh.empleado.id'], name=op.f('fk_justificacion_ausencia_id_empleado_empleado'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_justificacion_ausencia')),
    schema='rrhh'
    )
    op.create_table('vacacion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_empleado', sa.Integer(), nullable=False),
    sa.Column('gestion', sa.Integer(), nullable=False, comment='Año de la gestión (ej: 2026)'),
    sa.Column('horas_correspondientes', sa.Numeric(precision=6, scale=1), nullable=False, comment='Horas totales asignadas (LGT + feriados trabajados + cumpleaños transferido)'),
    sa.Column('horas_goce_haber', sa.Numeric(precision=6, scale=1), nullable=False, comment='Horas disponibles con pago de salario'),
    sa.Column('horas_sin_goce_haber', sa.Numeric(precision=6, scale=1), nullable=False, comment='Horas disponibles sin pago de salario'),
    sa.Column('horas_tomadas', sa.Numeric(precision=6, scale=1), nullable=False, comment='Total de horas consumidas'),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_empleado'], ['rrhh.empleado.id'], name=op.f('fk_vacacion_id_empleado_empleado'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vacacion')),
    sa.UniqueConstraint('id_empleado', 'gestion', name='uq_vacacion_empleado_gestion'),
    schema='rrhh'
    )
    op.create_table('detalle_vacacion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_vacacion', sa.Integer(), nullable=False),
    sa.Column('id_justificacion', sa.Integer(), nullable=True, comment='Solo se usa cuando tipo_vacacion=licencia_accidente'),
    sa.Column('fecha_inicio', sa.Date(), nullable=False, comment='Primer día de vacaciones'),
    sa.Column('fecha_fin', sa.Date(), nullable=False, comment='Último día de vacaciones'),
    sa.Column('horas_habiles', sa.Numeric(precision=6, scale=1), nullable=False, comment='Horas hábiles de vacación (calculadas por backend)'),
    sa.Column('tipo_vacacion', sa.Enum('goce_de_haber', 'sin_goce_de_haber', 'licencia_accidente', name='tipo_vacacion_enum', native_enum=True, create_constraint=True, schema='rrhh'), nullable=False),
    sa.Column('estado', sa.Enum('solicitado', 'aprobado', 'tomado', 'rechazado', 'cancelado', name='estado_detalle_vacacion_enum', native_enum=True, create_constraint=True, schema='rrhh'), nullable=False),
    sa.Column('id_aprobado_por', sa.Integer(), nullable=True, comment='ID del empleado que aprobó/rechazó'),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_aprobado_por'], ['rrhh.empleado.id'], name=op.f('fk_detalle_vacacion_id_aprobado_por_empleado'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_justificacion'], ['rrhh.justificacion_ausencia.id'], name=op.f('fk_detalle_vacacion_id_justificacion_justificacion_ausencia'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_vacacion'], ['rrhh.vacacion.id'], name=op.f('fk_detalle_vacacion_id_vacacion_vacacion'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_detalle_vacacion')),
    schema='rrhh'
    )

    # Add foreign key constraint to asistencia_diaria
    op.execute("""
        ALTER TABLE rrhh.asistencia_diaria
        ADD CONSTRAINT fk_asistencia_justificacion
        FOREIGN KEY (id_justificacion)
        REFERENCES rrhh.justificacion_ausencia(id)
        ON DELETE SET NULL;
    """)

    # Create function fn_horas_vacacion_lgt
    op.execute("""
        CREATE OR REPLACE FUNCTION rrhh.fn_horas_vacacion_lgt(
            p_fecha_ingreso  DATE,
            p_fecha_calculo  DATE DEFAULT CURRENT_DATE
        )
        RETURNS NUMERIC(6,1)
        LANGUAGE plpgsql
        IMMUTABLE
        AS $$
        DECLARE
            v_anios NUMERIC;
        BEGIN
            v_anios := EXTRACT(YEAR FROM AGE(p_fecha_calculo, p_fecha_ingreso))
                     + EXTRACT(MONTH FROM AGE(p_fecha_calculo, p_fecha_ingreso)) / 12.0;

            RETURN CASE
                WHEN v_anios < 1.0  THEN 0.0
                WHEN v_anios < 5.0  THEN 120.0
                WHEN v_anios < 10.0 THEN 160.0
                ELSE                     240.0
            END;
        END;
        $$;
    """)

    # Create view v_resumen_vacaciones
    op.execute("""
        CREATE OR REPLACE VIEW rrhh.v_resumen_vacaciones AS
        SELECT
            e.id                        AS id_empleado,
            e.nombres || ' ' || e.apellidos AS nombre_completo,
            e.fecha_ingreso,
            c.nombre                    AS cargo,
            c.es_cargo_confianza,
            v.gestion,
            v.horas_correspondientes    AS total_horas_asignadas,
            v.horas_goce_haber          AS horas_goce_disponibles,
            v.horas_sin_goce_haber      AS horas_sin_goce_disponibles,
            v.horas_tomadas             AS total_horas_tomadas,
            (v.horas_correspondientes - v.horas_tomadas)  AS horas_pendientes_total,
            ROUND(v.horas_correspondientes / 8.0, 1) AS dias_asignados,
            ROUND(v.horas_tomadas        / 8.0, 1)   AS dias_tomados,
            ROUND((v.horas_correspondientes - v.horas_tomadas) / 8.0, 1)   AS dias_pendientes,
            rrhh.fn_horas_vacacion_lgt(e.fecha_ingreso, MAKE_DATE(v.gestion, 12, 31)) AS horas_segun_antiguedad,
            v.observacion
        FROM rrhh.vacacion v
        JOIN rrhh.empleado e ON e.id = v.id_empleado
        JOIN rrhh.cargo    c ON c.id = e.id_cargo;
    """)

    # ### end Alembic commands ###


def downgrade() -> None:
    # Drop view
    op.execute("DROP VIEW IF EXISTS rrhh.v_resumen_vacaciones;")

    # Drop function
    op.execute("DROP FUNCTION IF EXISTS rrhh.fn_horas_vacacion_lgt(DATE, DATE);")

    # Drop foreign key constraint from asistencia_diaria
    op.execute("""
        ALTER TABLE rrhh.asistencia_diaria
        DROP CONSTRAINT IF EXISTS fk_asistencia_justificacion;
    """)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalle_vacacion', schema='rrhh')
    op.drop_table('vacacion', schema='rrhh')
    op.drop_table('justificacion_ausencia', schema='rrhh')
    op.drop_table('beneficio_cumpleanos', schema='rrhh')
    op.drop_index(op.f('ix_rrhh_dia_festivo_fecha'), table_name='dia_festivo', schema='rrhh')
    op.drop_table('dia_festivo', schema='rrhh')
    # ### end Alembic commands ###

